spring:
    application:
        name: awesome-user-server
    cloud:
        consul:
            host: localhost
            port: 8500
            discovery:
                enabled: true
                register: true
                healthCheckInterval: 10s
                instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
            config:
              watch:
                enabled: true
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/andy_test?serverTimezone=UTC
        username: Andy
        password: 123456
    sleuth:
        sampler:
            probability: 1.0
mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: awesome.user.server

server:
    port: 9401
logging:
    pattern:
        level: '[%X{X-B3-TraceId}/%X{X-B3-SpanId}] %-5p [%t] %C{2} - %m%n'
management:
    endpoints:
        web:
            exposure:
                include: metrics,env,beans,mappings,health