spring:
    application:
        name: awesome-message-consumer-server
    cloud:
        consul:
            host: localhost
            port: 8500
            discovery:
                enabled: true
                register: true
                healthCheckInterval: 10s
                instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
            config:
              watch:
                enabled: true
        stream:
              default-binder: kafka
              bindings:
                sms_message_consumer:
                  destination: sms-message
                  group: message-sever-consumer
    sleuth:
        sampler:
            probability: 1.0

server:
    port: 9501
logging:
    pattern:
        level: '[%X{X-B3-TraceId}/%X{X-B3-SpanId}] %-5p [%t] %C{2} - %m%n'
management:
    endpoints:
        web:
            exposure:
                include: metrics,env,beans,mappings,health